spring:
  application:
    name: dzy-crawler-dev
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://127.0.0.1:27017/test}
  redis:
    host: ${REDIS_IP:127.0.0.1}
    port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

smzdm:
  spider:
    threadCount: 2
  ranking:
    size: 50

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8889/xxl-job
    executor:
      app-name: ${spring.application.name}
      port: 9999
      log-path: logs/xxl-job
      log-retention-days: 30

host: localhost:8080

email:
  receive: xxx@qq.com
  htmlPath: smzdm.html
  settingPath: mail.setting

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    # 下面选项建议打开，以监控 http 请求的 P99/P95 等，具体的时间分布可以根据实际情况设置
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
    tags:
      application: ${spring.application.name}