spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://127.0.0.1:27017/test}
  redis:
    host: ${REDIS_IP:127.0.0.1}
    port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

smzdm:
  ranking:
    size: 50